// Create context menu on installation
chrome.runtime.onInstalled.addListener(() => {
    chrome.contextMenus.create({
        id: "checkAISlop",
        title: "Check if AI Slop",
        contexts: ["selection"]
    });
    
    console.log('AI Slop Detector installed!');
});

// Handle context menu clicks
chrome.contextMenus.onClicked.addListener((info, tab) => {
    if (info.menuItemId === "checkAISlop" && info.selectionText) {
        const selectedText = info.selectionText.trim();
        
        // Send message to content script to show loading notification
        chrome.tabs.sendMessage(tab.id, {
            type: 'SHOW_ANALYZING'
        }).catch(err => {
            console.log('Content script not ready:', err);
        });
        
        // Open the popup and send the text to analyze
        // Note: We can't programmatically open popup, so we show a notification instead
        showNotification(
            'Open Extension',
            'Please click the extension icon to analyze the selected text.',
            'info',
            selectedText
        );
    }
});

// Show notification with result
function showResultNotification(classification, text) {
    let title, message, iconPath;
    
    if (classification === 'ai') {
        title = '🤖 AI-Generated';
        message = 'This text appears to be generated by AI.';
        iconPath = 'icons/icon128.png';
    } else if (classification === 'human') {
        title = '✍️ Human-Written';
        message = 'This text appears to be written by a human.';
        iconPath = 'icons/icon128.png';
    } else {
        title = '❓ Uncertain';
        message = 'Could not determine classification.';
        iconPath = 'icons/icon128.png';
    }
    
    // Add text preview
    const preview = text.length > 100 ? text.substring(0, 100) + '...' : text;
    message += `\n\nText: "${preview}"`;
    
    chrome.notifications.create({
        type: 'basic',
        iconUrl: iconPath,
        title: title,
        message: message,
        priority: 2
    });
}

// Generic notification with stored text
function showNotification(title, message, type = 'info', selectedText = null) {
    // Store selected text for popup to retrieve
    if (selectedText) {
        chrome.storage.local.set({ pendingText: selectedText });
    }
    
    chrome.notifications.create({
        type: 'basic',
        iconUrl: 'icons/icon128.png',
        title: title,
        message: message,
        priority: type === 'error' ? 2 : 1
    });
}

// Listen for messages from popup
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if (message.type === 'MODEL_LOADED') {
        console.log('Model loaded in popup');
        sendResponse({ status: 'acknowledged' });
    } else if (message.type === 'GET_PENDING_TEXT') {
        // Send pending text to popup
        chrome.storage.local.get(['pendingText'], (result) => {
            sendResponse({ text: result.pendingText || null });
            // Clear pending text
            chrome.storage.local.remove(['pendingText']);
        });
        return true; // Keep channel open for async response
    } else if (message.type === 'ANALYSIS_COMPLETE') {
        // Popup completed analysis, show result in content script if tab is available
        if (message.tabId) {
            chrome.tabs.sendMessage(message.tabId, {
                type: 'SHOW_RESULT',
                classification: message.classification,
                text: message.text
            }).catch(err => {
                console.log('Could not send to content script:', err);
            });
        }
        sendResponse({ status: 'acknowledged' });
    }
    
    return false;
});