// Listen for messages from background script
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if (message.type === 'SHOW_ANALYZING') {
        showToast('🔍 Analyzing text...', 'loading');
    } else if (message.type === 'SHOW_RESULT') {
        showResultToast(message.classification, message.text);
    }
});

// Show toast notification on the page
function showToast(message, type = 'info') {
    // Remove existing toast if any
    const existingToast = document.getElementById('ai-slop-detector-toast');
    if (existingToast) {
        existingToast.remove();
    }

    // Create toast element
    const toast = document.createElement('div');
    toast.id = 'ai-slop-detector-toast';
    toast.style.cssText = `
        position: fixed;
        top: 20px;
        right: 20px;
        background: ${type === 'ai' ? '#fff3e0' : type === 'human' ? '#e8f5e9' : '#fff'};
        border: 2px solid ${type === 'ai' ? '#ff9800' : type === 'human' ? '#4caf50' : '#667eea'};
        color: #333;
        padding: 16px 20px;
        border-radius: 8px;
        box-shadow: 0 4px 12px rgba(0,0,0,0.15);
        z-index: 999999;
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        font-size: 14px;
        max-width: 350px;
        animation: slideIn 0.3s ease;
    `;
    
    toast.textContent = message;
    document.body.appendChild(toast);

    // Add animation
    const style = document.createElement('style');
    style.textContent = `
        @keyframes slideIn {
            from {
                transform: translateX(400px);
                opacity: 0;
            }
            to {
                transform: translateX(0);
                opacity: 1;
            }
        }
    `;
    document.head.appendChild(style);

    // Auto remove after 5 seconds
    setTimeout(() => {
        toast.style.animation = 'slideIn 0.3s ease reverse';
        setTimeout(() => toast.remove(), 300);
    }, 5000);
}

// Show result toast
function showResultToast(classification, text) {
    let message, type;
    
    if (classification === 'ai') {
        message = '🤖 AI-Generated: This text appears to be generated by AI.';
        type = 'ai';
    } else if (classification === 'human') {
        message = '✍️ Human-Written: This text appears to be written by a human.';
        type = 'human';
    } else {
        message = '❓ Uncertain: Could not determine classification.';
        type = 'info';
    }
    
    showToast(message, type);
}